services:
  moodle:
    image: bitnami/moodle:4.4.5-debian-12-r0
    container_name: moodle
    ports:
      - "${MOODLE_HTTP_PORT}:8080"
      - "${MOODLE_HTTPS_PORT}:8443"
    environment:
      - MOODLE_USERNAME=${MOODLE_USERNAME}
      - MOODLE_PASSWORD=${MOODLE_PASSWORD}
      - MOODLE_EMAIL=${MOODLE_EMAIL}
      - MOODLE_SITE_NAME=${MOODLE_SITE_NAME}
      - MOODLE_DB_TYPE=mysqli
      - MOODLE_DB_HOST=${DB_HOST}
      - MOODLE_DB_USER=${DB_USER}
      - MOODLE_DB_PASSWORD=${DB_PASSWORD}
      - MOODLE_DB_NAME=${DB_NAME}
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
    depends_on:
      - mariadb

  mariadb:
    image: bitnami/mariadb:latest
    container_name: moodle_db
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    volumes:
      - mariadb_data:/bitnami/mariadb

volumes:
  moodle_data:
  moodledata_data:
  mariadb_data:
