services:
  moodle:
    image: bitnamilegacy/moodle:5.0.2
    restart: unless-stopped
    container_name: moodle
    ports:
      - "${MOODLE_HTTP_PORT}:8080"
      - "${MOODLE_HTTPS_PORT}:8443"
    environment:
      - MOODLE_USERNAME=${MOODLE_USERNAME}
      - MOODLE_PASSWORD=${MOODLE_PASSWORD}
      - MOODLE_EMAIL=${MOODLE_EMAIL}
      - MOODLE_SITE_NAME=${MOODLE_SITE_NAME}
      - MOODLE_DATABASE_TYPE=mysqli
      - MOODLE_DATABASE_HOST=${DB_HOST}
      - MOODLE_DATABASE_PORT_NUMBER=${DB_PORT}
      - MOODLE_DATABASE_USER=${DB_USER}
      - MOODLE_DATABASE_PASSWORD=${DB_PASSWORD}
      - MOODLE_DATABASE_NAME=${DB_NAME}
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
    depends_on:
      - mariadb
    networks:
      - moodle_network

  mariadb:
    image: bitnami/mariadb:latest
    container_name: moodle_db
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    volumes:
      - mariadb_data:/bitnami/mariadb
    networks:
      - moodle_network

volumes:
  moodle_data:
  moodledata_data:
  mariadb_data:

networks:
  moodle_network:
    driver: bridge
